import { defineConfig } from "oxlint";

import type { OxlintConfig } from "oxlint";

/* ============================================================================================= */

const oxlintConfig: OxlintConfig = defineConfig({
  categories: {
    correctness: "error",
    nursery: "warn",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  env: {
    browser: true,
    builtin: true,
    node: true,
  },
  jsPlugins: [
    {
      name: "react-hooks-js",
      specifier: "eslint-plugin-react-hooks",
    },
  ],
  options: {
    denyWarnings: false,
    reportUnusedDisableDirectives: "error",
    respectEslintDisableDirectives: false,
    typeAware: true,
    typeCheck: false,
  },
  plugins: [
    "eslint",
    "import",
    "jsdoc",
    "jsx-a11y",
    "nextjs",
    "node",
    "oxc",
    "promise",
    "react",
    "react-perf",
    "typescript",
    "unicorn",
  ],
  rules: {
    "capitalized-comments": [
      "error",
      "never",
      {
        block: {
          ignorePattern: "/\\/\\*\\s*=+\\s*[\\r\\n]+(?:[\\s\\S]*?)[\\r\\n]+\\s*=+\\s*\\*\\//m",
        },
        ignorePattern: "^([A-Z]{2,}|[A-Z][A-Z0-9_-]*)(\\b|:)",
      },
    ],
    "eslint/class-methods-use-this": "off",
    "eslint/complexity": ["error", { max: 30 }],
    "eslint/id-length": [
      "error",
      {
        checkGeneric: false,
        exceptions: ["a", "b", "h", "i", "j", "k", "K", "m", "p", "T", "U", "w", "x", "y", "z"],
      },
    ],
    "eslint/init-declarations": "off",
    "eslint/max-lines-per-function": [
      "error",
      { max: 120, skipBlankLines: true, skipComments: true },
    ],
    "eslint/max-params": ["error", { max: 4 }],
    "eslint/max-statements": ["error", { max: 40 }],
    "eslint/no-await-in-loop": "off",
    "eslint/no-continue": "off",
    "eslint/no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "eslint/no-magic-numbers": "off",
    "eslint/no-plusplus": "off",
    "eslint/no-ternary": "off",
    "eslint/no-undefined": "off",
    "eslint/no-underscore-dangle": ["error", { allow: ["__dirname", "__filename"] }],
    "eslint/no-use-before-define": "off",
    "eslint/no-warning-comments": "off",
    "eslint/require-unicode-regexp": "off",
    "eslint/sort-imports": "off",
    "eslint/sort-keys": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/max-dependencies": ["error", { max: 30 }],
    "import/no-default-export": "off",
    "import/no-named-default": "off",
    "import/no-named-export": "off",
    "import/no-nodejs-modules": "off",
    "import/no-unassigned-import": ["error", { allow: ["**/*.css"] }],
    "jsdoc/require-param-type": "off",
    "jsdoc/require-returns": "off",
    "jsdoc/require-returns-type": "off",
    "no-unused-vars": [
      "error",
      {
        args: "all",
        argsIgnorePattern: "^_",
        caughtErrors: "all",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
      },
    ],
    "oxc/no-async-await": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "promise/avoid-new": "off",
    "react/forbid-component-props": ["error", { forbid: ["style"] }],
    "react/jsx-filename-extension": ["error", { extensions: ["jsx", "tsx"] }],
    "react/jsx-pascal-case": ["error", { allowAllCaps: true }],
    "react/jsx-props-no-spreading": "off",
    "react/jsx-max-depth": ["error", { max: 6 }],
    "react/no-multi-comp": ["error", { ignoreStateless: true }],
    "react/only-export-components": [
      "error",
      {
        allowExportNames: [
          "dynamicParams",
          "generateMetadata",
          "generateStaticParams",
          "metadata",
          "variants",
        ],
      },
    ],
    "react/react-in-jsx-scope": "off",
    "react-hooks-js/error-boundaries": "error",
    "react-hooks-js/config": "error",
    "react-hooks-js/globals": "error",
    "react-hooks-js/immutability": "error",
    "react-hooks-js/incompatible-library": "error",
    "react-hooks-js/preserve-manual-memoization": "error",
    "react-hooks-js/purity": "error",
    "react-hooks-js/refs": "error",
    "react-hooks-js/set-state-in-effect": "error",
    "react-hooks-js/set-state-in-render": "error",
    "react-hooks-js/static-components": "error",
    "react-hooks-js/unsupported-syntax": "error",
    "react-hooks-js/use-memo": "error",
    "react-perf/jsx-no-jsx-as-prop": "off",
    "react-perf/jsx-no-new-array-as-prop": "off",
    "react-perf/jsx-no-new-function-as-prop": "off",
    "react-perf/jsx-no-new-object-as-prop": "off",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "typescript/no-inferrable-types": "off",
    "typescript/no-unnecessary-condition": "off",
    "typescript/no-unnecessary-type-parameters": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/no-useless-default-assignment": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/strict-boolean-expressions": "off",
    "unicorn/no-null": "off",
    "unicorn/no-lonely-if": "off",
    "unicorn/switch-case-braces": "off",
  },
});

/* ============================================================================================= */

export default oxlintConfig;
