# Purpose: Deploy docs to GitHub Pages
# Trigger: workflow_call (CI), workflow_dispatch (manual)

name: DOCS

on:
  # trigger 1
  workflow_call:
    # this will have the caller workflow's `github` context (full)

  # trigger 2
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to deploy (leave empty for latest)"
        required: false

# permission for the `workflow_call` will be granted from the caller workflow
# persmission for the `workflow_dispatch` granted here
permissions:
  id-token: write # authenticate with OIDC for secure deployments
  contents: read # checkout code
  pages: write # deploy to GitHub Pages

#
jobs:
  #
  #
  #
  check_version:
    # if repository owner is `JadejaHQ`
    # |-- if `workflow_dispatch` (manuall trigger)
    # `-- if `workflow_call` (from `CI`)
    #     - base branch is `main`
    #     - `pull_request` is merged
    if: >
      github.repository_owner == 'JadejaHQ' && (
        github.event_name == 'workflow_dispatch' ||
        (
          github.base_ref == 'main' &&
          github.event_name == 'pull_request' &&
          github.event.action == 'closed' &&
          github.event.pull_request.merged == true
        )
      )

    name: Check Version

    runs-on: ubuntu-latest

    # share data with dependent jobs
    outputs:
      version_changed: ${{ steps.docs_changed.outputs.version_changed }}
      sha: ${{ inputs.commit_sha || github.event.pull_request.head.sha }}

    steps:
      # 1
      - name: Checkout the repository
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v6
        with:
          # fetch commits history from the base branch
          # `n`: no. of commits
          # `n = 0`: full history
          fetch-depth: 97 # if more than 97 commits, then this need to be bumped

          # `workflow_dispatch` (manual trigger)
          # |- use base branch SHA (latest)
          # `- use user input SHA for rollback
          #
          # `pull_request`
          # `- use head branch SHA
          ref: ${{ inputs.commit_sha || github.event.pull_request.head.sha }}

      # 2. skip if not triggered by `pull_request`
      - name: Check docs version change
        id: docs_changed
        if: github.event_name == 'pull_request'
        run: |
          # Compare commits
          CHANGED_FILES=$(git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }})
          if echo "$CHANGED_FILES" | grep -q "^apps/docs/package.json$"; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Proceeding with deployment."
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Skipping deployment."
          fi

  #
  #
  #
  deploy:
    # runs after `check_version` job
    needs: check_version

    # `check_version` job must succeed
    # docs version must be chagned
    if: >
      needs.check_version.result == 'success' && (
        github.event_name == 'workflow_dispatch' || (
          needs.check_version.outputs.version_changed == 'true'
        )
      )

    name: Deploy docs to github pages

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          ref: ${{ needs.check_version.outputs.sha }}

      # 2. to provide access to setup-node's `cache: pnpm`
      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: 10.x.x
          run_install: false
          cache: true

      # 3
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml # root lockfile

      # 4. prevent when lockfile is out of sync
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      # 5
      - name: Build docs
        run: pnpm build --filter=shilpcss-docs

      # 6
      - name: Setup Pages
        uses: actions/configure-pages@v6

      # 7
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: apps/docs/dist

      # 8
      - name: Deploy to GitHub Pages
        id: deployment # required so `environment.url` can read `page_url`
        uses: actions/deploy-pages@v5
